---
name: Create release PR

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * 3'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Create PR
        run: gh pr create --title "Release week \#$(date +%V)" --body "Automatically created PR to merge main into release" --base release --head main
