---
name: Create release PR

permissions:
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * 3'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Create PR
        run: gh pr create --title "Release week $(date +%V)" --body "Automatically created PR to merge main into release" --base release --head main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
