---
name: Run renovate-config-validator

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: Validate config 
        run: |
          docker run --entrypoint=renovate-config-validator --volume "$(pwd):/tmp" renovate/renovate:slim /tmp/default.json
